
import { Question, QuestionType } from './types';

export const QUESTIONS: Question[] = [
  // 50 MCQ Questions
  ...Array.from({ length: 50 }, (_, i) => ({
    id: i + 1,
    type: QuestionType.MCQ,
    question: {
      en: [
        "What is the base of the Decimal number system?",
        "What is the base of the Binary number system?",
        "A 'Bit' is short for what term?",
        "What is the weight of the LSB in an 8-bit binary number?",
        "Which gate is also known as an Inverter?",
        "In Boolean Algebra, what does A + 0 equal?",
        "In Boolean Algebra, what does A · 1 equal?",
        "Which gate produces a HIGH output only when all inputs are HIGH?",
        "Which gate produces a HIGH output when at least one input is HIGH?",
        "What is the binary representation of the decimal number 9?",
        "What is the base of the Octal number system?",
        "What is the base of the Hexadecimal number system?",
        "How many bits are in a 'Nibble'?",
        "How many bits are in a standard 'Byte'?",
        "What does LSB stand for?",
        "What does MSB stand for?",
        "What is the result of 1 + 1 in binary?",
        "What is the result of 1 · 0 in binary?",
        "The Boolean expression Q = A · B represents which gate?",
        "The Boolean expression Q = A + B represents which gate?",
        "According to DeMorgan's Theorem, (A · B)' is equal to?",
        "According to DeMorgan's Theorem, (A + B)' is equal to?",
        "In BCD code, how many bits represent one decimal digit?",
        "Which code is a reflected binary code where only one bit changes at a time?",
        "What is the decimal value of the binary number 1010?",
        "The result of (A')' is?",
        "What is the 1's complement of 1010?",
        "What is the 2's complement of 1010?",
        "Which gate is the inverse of the AND gate?",
        "Which gate is the inverse of the OR gate?",
        "What is the output of an XOR gate when inputs are 1 and 1?",
        "What is the output of an XNOR gate when inputs are 0 and 0?",
        "Boolean Law: A + A = ?",
        "Boolean Law: A · A = ?",
        "Boolean Law: A + 1 = ?",
        "Boolean Law: A · 0 = ?",
        "SOP stands for?",
        "POS stands for?",
        "In SOP, a product term that contains all variables is called a?",
        "In POS, a sum term that contains all variables is called a?",
        "A 3-variable K-Map has how many cells?",
        "A 4-variable K-Map has how many cells?",
        "Who developed the system of mathematical logic used in digital circuits?",
        "What is the binary code for decimal 5?",
        "In the Hexadecimal system, what letter represents the value 10?",
        "In the Hexadecimal system, what letter represents the value 15?",
        "Binary multiplication 10 * 11 equals?",
        "Binary addition 11 + 1 equals?",
        "Binary subtraction 10 - 1 equals?",
        "Which logic level is usually represented by 0 volts?"
      ][i],
      ar: [
        "ما هو أساس النظام العددي العشري؟",
        "ما هو أساس النظام العددي الثنائي؟",
        "كلمة 'Bit' هي اختصار لأي مصطلح؟",
        "ما هو وزن الخانة الأقل أهمية (LSB) في عدد ثنائي من 8 بت؟",
        "أي بوابة تُعرف أيضاً باسم العاكس (Inverter)؟",
        "في جبر بول، ماذا يساوي A + 0؟",
        "في جبر بول، ماذا يساوي A · 1؟",
        "أي بوابة تعطي خرجاً عالياً (HIGH) فقط عندما تكون جميع المداخل عالية؟",
        "أي بوابة تعطي خرجاً عالياً عندما يكون مدخل واحد على الأقل عالياً؟",
        "ما هو التمثيل الثنائي للرقم العشري 9؟",
        "ما هو أساس النظام العددي الثماني؟",
        "ما هو أساس النظام العددي السداسي عشر؟",
        "كم عدد البتات في 'النيبل' (Nibble)؟",
        "كم عدد البتات في 'البايت' القياسي؟",
        "إلى ماذا يرمز الاختصار LSB؟",
        "إلى ماذا يرمز الاختصار MSB؟",
        "ما هي نتيجة 1 + 1 في النظام الثنائي؟",
        "ما هي نتيجة 1 · 0 في النظام الثنائي؟",
        "التعبير البولي Q = A · B يمثل أي بوابة؟",
        "التعبير البولي Q = A + B يمثل أي بوابة؟",
        "وفقاً لنظرية ديمورغان، (A · B)' يساوي؟",
        "وفقاً لنظرية ديمورغان، (A + B)' يساوي؟",
        "في نظام BCD، كم عدد البتات التي تمثل رقماً عشرياً واحداً؟",
        "أي كود هو كود ثنائي انعكاسي حيث يتغير بت واحد فقط في كل مرة؟",
        "ما هي القيمة العشرية للرقم الثنائي 1010؟",
        "ما هي نتيجة (A')'؟",
        "ما هو متمم الآحاد للرقم 1010؟",
        "ما هو متمم الثنائيات للرقم 1010؟",
        "أي بوابة هي عكس بوابة AND؟",
        "أي بوابة هي عكس بوابة OR؟",
        "ما هو خرج بوابة XOR عندما تكون المداخل 1 و 1؟",
        "ما هو خرج بوابة XNOR عندما تكون المداخل 0 و 0؟",
        "قانون بولي: A + A = ؟",
        "قانون بولي: A · A = ؟",
        "قانون بولي: A + 1 = ؟",
        "قانون بولي: A · 0 = ؟",
        "ماذا يعني اختصار SOP؟",
        "ماذا يعني اختصار POS؟",
        "في SOP، يسمى حد الضرب الذي يحتوي على جميع المتغيرات بـ؟",
        "في POS، يسمى حد الجمع الذي يحتوي على جميع المتغيرات بـ؟",
        "خريطة كارنو لـ 3 متغيرات تحتوي على كم خلية؟",
        "خريطة كارنو لـ 4 متغيرات تحتوي على كم خلية؟",
        "من طور نظام المنطق الرياضي المستخدم في الدوائر الرقمية؟",
        "ما هو الكود الثنائي للرقم العشري 5؟",
        "في النظام السداسي عشر، أي حرف يمثل القيمة 10؟",
        "في النظام السداسي عشر، أي حرف يمثل القيمة 15؟",
        "الضرب الثنائي 10 * 11 يساوي؟",
        "الجمع الثنائي 11 + 1 يساوي؟",
        "الطرح الثنائي 10 - 1 يساوي؟",
        "أي مستوى منطقي يتم تمثيله عادةً بـ 0 فولت؟"
      ][i]
    },
    options: {
      en: [
        ["2", "8", "10", "16"], ["2", "8", "10", "16"], ["Binary Digit", "Basic Unit", "Binary Tool", "Bit Rate"], ["1", "2", "4", "128"], ["AND", "OR", "NOT", "NAND"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["OR", "AND", "XOR", "NOR"], ["AND", "OR", "NOT", "NAND"], ["1000", "1001", "1010", "1111"], ["8", "10", "16", "2"], ["16", "10", "8", "2"], ["2", "4", "8", "16"], ["4", "8", "16", "32"], ["Least Significant Bit", "Low System Bit", "Last Single Bit", "Level Start Bit"], ["Main System Bit", "Most Significant Bit", "Memory Start Bit", "Max System Bit"], ["0", "1", "10", "11"], ["0", "1", "10", "11"], ["AND", "OR", "NOT", "NAND"], ["AND", "OR", "NOT", "NAND"], ["A' + B'", "A' · B'", "A + B", "A · B"], ["A' + B'", "A' · B'", "A + B", "A · B"], ["1", "2", "4", "8"], ["Binary", "BCD", "Gray", "ASCII"], ["8", "10", "12", "15"], ["0", "1", "A", "A'"], ["0101", "1111", "0000", "1011"], ["0101", "0110", "1111", "0000"], ["NAND", "NOR", "XOR", "XNOR"], ["NAND", "NOR", "XOR", "XNOR"], ["0", "1", "10", "None"], ["0", "1", "10", "None"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["Sum of Products", "Standard of Parts", "Single of Power", "System of Pulse"], ["Product of Sums", "Point of Sale", "Power of System", "Part of Standard"], ["Minterm", "Maxterm", "Sumterm", "Productterm"], ["Minterm", "Maxterm", "Sumterm", "Productterm"], ["4", "6", "8", "16"], ["8", "12", "16", "32"], ["Claude Shannon", "George Boole", "Alan Turing", "John von Neumann"], ["100", "101", "110", "111"], ["A", "B", "C", "F"], ["A", "C", "E", "F"], ["110", "101", "111", "100"], ["100", "111", "10", "101"], ["1", "0", "11", "10"], ["HIGH", "LOW", "VCC", "True"]
      ][i],
      ar: [
        ["2", "8", "10", "16"], ["2", "8", "10", "16"], ["رقم ثنائي", "وحدة أساسية", "أداة ثنائية", "معدل البت"], ["1", "2", "4", "128"], ["AND", "OR", "NOT", "NAND"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["OR", "AND", "XOR", "NOR"], ["AND", "OR", "NOT", "NAND"], ["1000", "1001", "1010", "1111"], ["8", "10", "16", "2"], ["16", "10", "8", "2"], ["2", "4", "8", "16"], ["4", "8", "16", "32"], ["البت الأقل أهمية", "بت النظام المنخفض", "البت الفردي الأخير", "بت بداية المستوى"], ["بت النظام الرئيسي", "البت الأكثر أهمية", "بت بداية الذاكرة", "بت النظام الأقصى"], ["0", "1", "10", "11"], ["0", "1", "10", "11"], ["AND", "OR", "NOT", "NAND"], ["AND", "OR", "NOT", "NAND"], ["A' + B'", "A' · B'", "A + B", "A · B"], ["A' + B'", "A' · B'", "A + B", "A · B"], ["1", "2", "4", "8"], ["Binary", "BCD", "Gray", "ASCII"], ["8", "10", "12", "15"], ["0", "1", "A", "A'"], ["0101", "1111", "0000", "1011"], ["0101", "0110", "1111", "0000"], ["NAND", "NOR", "XOR", "XNOR"], ["NAND", "NOR", "XOR", "XNOR"], ["0", "1", "10", "لا شيء"], ["0", "1", "10", "لا شيء"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["0", "1", "A", "A'"], ["مجموع حواصل الضرب", "معيار الأجزاء", "منفرد القوة", "نظام النبض"], ["حاصل ضرب المجاميع", "نقطة البيع", "قوة النظام", "جزء من المعيار"], ["Minterm", "Maxterm", "Sumterm", "Productterm"], ["Minterm", "Maxterm", "Sumterm", "Productterm"], ["4", "6", "8", "16"], ["8", "12", "16", "32"], ["كلود شانون", "جورج بول", "ألان تورينج", "جون فون نيومان"], ["100", "101", "110", "111"], ["A", "B", "C", "F"], ["A", "C", "E", "F"], ["110", "101", "111", "100"], ["100", "111", "10", "101"], ["1", "0", "11", "10"], ["عالي", "منخفض", "VCC", "صح"]
      ][i]
    },
    correctAnswer: [2, 0, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2, 2, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 1, 0, 0, 0, 0, 1, 2, 2, 1, 1, 0, 3, 0, 0, 0, 1][i]
  })),

  // 25 True/False Questions
  ...Array.from({ length: 25 }, (_, i) => ({
    id: 51 + i,
    type: QuestionType.TRUE_FALSE,
    question: {
      en: [
        "Analog signals are continuous in both values and time.",
        "Digital signals have only two discrete levels, usually 0 and 1.",
        "The base of the Binary system is 10.",
        "A Byte consists of 8 bits.",
        "The NOT gate produces an output that is the same as the input.",
        "The AND gate output is HIGH only when all inputs are HIGH.",
        "In Boolean Algebra, A + A' = 1.",
        "In Boolean Algebra, A · A' = 1.",
        "The Gray code is used to reduce errors in digital transitions.",
        "A Nibble is larger than a Byte.",
        "The result of 1 + 0 in binary is 1.",
        "The result of 1 · 1 in binary is 0.",
        "DeMorgan's first theorem states that (A · B)' = A' + B'.",
        "SOP stands for Sum Of Products.",
        "A K-Map is a graphical tool used to simplify Boolean expressions.",
        "A 2-variable K-Map has 4 cells.",
        "The MSB is the rightmost bit in a binary number.",
        "The LSB is the leftmost bit in a binary number.",
        "NAND gate is a universal gate.",
        "NOR gate is a universal gate.",
        "Boolean Law: A + 1 = A.",
        "Boolean Law: A · 0 = 0.",
        "BCD stands for Binary Coded Decimal.",
        "Hexadecimal base is 16.",
        "The 1's complement of 1 is 0."
      ][i],
      ar: [
        "الإشارات التناظرية مستمرة في كل من القيمة والوقت.",
        "الإشارات الرقمية لها مستويان منفصلان فقط، عادةً 0 و 1.",
        "أساس النظام الثنائي هو 10.",
        "البايت يتكون من 8 بت.",
        "بوابة NOT تنتج خرجاً مطابقاً للمدخل.",
        "خرج بوابة AND يكون عالياً فقط عندما تكون جميع المداخل عالية.",
        "في جبر بول، A + A' = 1.",
        "في جبر بول، A · A' = 1.",
        "يستخدم كود غراي لتقليل الأخطاء في الانتقالات الرقمية.",
        "النيبل (Nibble) أكبر من البايت (Byte).",
        "نتيجة 1 + 0 في النظام الثنائي هي 1.",
        "نتيجة 1 · 1 في النظام الثنائي هي 0.",
        "تنص نظرية ديمورغان الأولى على أن (A · B)' = A' + B'.",
        "SOP تعني مجموع حواصل الضرب (Sum Of Products).",
        "خريطة كارنو هي أداة رسومية تستخدم لتبسيط التعبيرات البولية.",
        "خريطة كارنو لمتغيرين تحتوي على 4 خلايا.",
        "MSB هو البت الموجود في أقصى اليمين في الرقم الثنائي.",
        "LSB هو البت الموجود في أقصى اليسار في الرقم الثنائي.",
        "بوابة NAND هي بوابة عامة (Universal Gate).",
        "بوابة NOR هي بوابة عامة (Universal Gate).",
        "قانون بولي: A + 1 = A.",
        "قانون بولي: A · 0 = 0.",
        "BCD تعني العشري المشفر ثنائياً (Binary Coded Decimal).",
        "أساس النظام السداسي عشر هو 16.",
        "متمم الآحاد للرقم 1 هو 0."
      ][i]
    },
    correctAnswer: [0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0][i] // 0 for True, 1 for False
  }))
];
